# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:00
from __future__ import unicode_literals

from django.db import migrations


def load_questions(apps, schema_editor):
    Question = apps.get_model("question", "Question")
    QuestionLevel = apps.get_model("question", "QuestionLevel")

    questions = [
        {
            "Level": "xx",
            "Question_No": "1",
            "Qustion": "3.64/7",
            "Answer": "0.52",
        },
        {
            "Level": "xx",
            "Question_No": "2",
            "Qustion": "(9-(8-(3+0.5)*6))/(8-(\(1//3)\+\(1@1//2)\)^2*6)",
            "Answer": "\(1@4//23\)",
        },
        {
            "Level": "xx",
            "Question_No": "3",
            "Qustion": "There are a basket of apples. If every kid gets 9 apples, there won’t be any remainder. If every kid gets 6 apples, there will be 18 apples remained. How many kids are there?",
            "Answer": "6",
        },
    ]

    for question in questions:
        level, created = QuestionLevel.objects.get_or_create(title=question['Level'])

        Question.objects.create(
            level=level,
            question=question['Qustion'],
            order=question['Question_No'],
            answer=question['Answer'])


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_questions),
    ]
