# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20160826_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='format',
            field=models.BooleanField(default=True),
        ),
    ]
