# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='format',
            new_name='is_equation',
        ),
    ]
